### PR TITLE
FIX #15

### LINKED ISSUE #15: Warning: setState(...): Can only update a mounting component.
```
Warning: setState(...): Can only update a mounting component. This usually means 
you called setState() outside componentWillMount() on the server. This is a no-op. 
```

### PR DESCRIPTION
**Pull request by sarovin**

### CODE REVIEW

**Comment by markusjwetzel** [comment]
Can we merge this? I also use react-loading with server side rendering and need this fix.

**Comment by pcgilday** [comment]
@fakiolinho Is there a reason this hasn't been merged or updated? We rely on this component, so I'd be happy to help out in any way I can.

**Comment by fakiolinho** [comment]
Yeah @pcgilday @markusjwetzel @sarovin you 're so right. I 'll make some changes and release it by tomorrow 😉

**Comment by pcgilday** [comment]
Awesome, thank you for your hard work here, it's a great component!

**Comment by sarovin** [comment]
Great

**Pull request closed without merging**
